# Generated by Django 4.0.3 on 2022-03-19 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('rated', models.CharField(max_length=200)),
                ('released', models.CharField(max_length=200)),
                ('runtime', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('actors', models.CharField(max_length=200)),
                ('plot', models.TextField(max_length=1000)),
                ('language', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('awards', models.CharField(max_length=200)),
                ('poster', models.URLField()),
                ('metascore', models.IntegerField()),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('imdb_votes', models.CharField(max_length=200)),
                ('imdb_id', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('dvd', models.CharField(max_length=200)),
                ('box_office', models.CharField(max_length=200)),
                ('production', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='movie.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
        ),
    ]
