# Generated by Django 4.0.3 on 2022-03-19 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_poster_movie_title_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='movie.movie'),
        ),
    ]
